JNG-4269 Proper mdoel name and version handling
BlackBeltTechnology/judo-meta-psm-jql pull request #47
Opened 2023-02-23 14:12 UTC by robertcsakany

JNG-4269 Proper mdoel name and version handling

2023-02-26 17:37 UTC, noherczeg requested changes

2023-02-26 17:37 UTC, noherczeg commented on osgi/src/main/java/hu/blackbelt/judo/meta/jql/osgi/JqlDslModelBundleTracker.java
> +                        log.error("Could not load Psm model: " + params.get(JqlDslModel.NAME) + " from bundle: " + trackedBundle.getBundleId(), e);
PSM?

2023-02-27 10:10 UTC, noherczeg approved these changes

2023-02-27 15:06 UTC, fmagnucz approved these changes

2023-02-27 16:40 UTC, merged