JNG-4497 Release judo meta jql
BlackBeltTechnology/judo-meta-psm-jql pull request #48
Opened 2023-02-28 10:29 UTC by gaborflorian

2023-02-28 11:05 UTC, noherczeg approved these changes

2023-02-28 11:24 UTC, Madmat8 approved these changes

2023-02-28 21:48 UTC, bencegelei requested changes

2023-02-28 21:48 UTC, bencegelei commented on pom.xml
> +                <version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:36 UTC, gaborflorian commented on pom.xml
> +                <version>1.2.11</version>
Requested by Robert

2023-03-01 10:02 UTC, robertcsakany approved these changes

2023-03-01 11:57 UTC, bencegelei approved these changes

2023-03-09 10:22 UTC, merged